"use client";
import { useState } from "react";
import * as XLSX from "xlsx";
import { Card, SectionTitle, Badge, Button } from "@/components/ui";
import { UploadCloud, CheckCircle2, AlertTriangle, FileSpreadsheet } from "lucide-react";

export default function ImportPage(){
 const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<any[]>([]); const [msg,setMsg]=useState("");
 async function handle(f:File){setFile(f); setMsg(""); const buf=await f.arrayBuffer(); const wb=XLSX.read(buf,{type:"array",cellDates:true}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null}).slice(0,10); setPreview(rows as any[]);}
 return <div className="space-y-6"><SectionTitle title="Importación STL / Excel" subtitle="Flujo demo: carga → análisis → vista previa → confirmación → informe"/><Card className="p-8"><label className="flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 p-12 text-center hover:border-slate-400"><UploadCloud className="h-10 w-10 text-[#002A54]"/><div className="mt-4 font-bold">Selecciona un archivo Excel</div><div className="mt-1 text-sm text-slate-500">XLSX / XLS · se analiza localmente en el navegador</div><input type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)handle(f)}}/></label>{file&&<div className="mt-5 flex items-center gap-3 rounded-xl bg-slate-50 p-4"><FileSpreadsheet className="h-5 w-5"/><div className="font-semibold">{file.name}</div><Badge tone="info">Analizado</Badge></div>}</Card>{preview.length>0&&<Card className="p-6"><SectionTitle title="Vista previa de estructura" subtitle="Antes de importar definitivamente"/><div className="overflow-auto rounded-xl border border-slate-200"><table className="min-w-full text-xs">{preview.map((r,i)=><tr key={i} className={i===0?"bg-slate-50 font-bold":""}>{r.map((v:any,j:number)=><td key={j} className="border-b border-slate-100 px-3 py-2">{String(v??"")}</td>)}</tr>)}</table></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setPreview([])}>Cancelar</Button><Button onClick={()=>setMsg("Vista previa confirmada. En producción este paso ejecutará la transacción de importación y registrará auditoría.")}>Confirmar importación</Button></div>{msg&&<div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{msg}</div>}</Card>}</div>
}
